[package]
name = "vm"
version = "0.1.0"
authors = ["romptroll <romptroll@hotmail.com>"]
edition = "2021"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minifb = "*"
lazy_static = "*"
num_enum = "*"